### ISSUE TITLE
what's your license?

### ISSUE THREAD

**Issue by wingchen** [mike-lloyd03/rust-in-the-middle#1]
I am interested in building off from your repo. So I am wonder what license you have for this project.
Thanks

**Comment by mike-lloyd03** [comment]
Hey thanks for your interest. I'd really like to see a command line MITM proxy come to life. This would come in handy at work actually. 

I wish I had time to get this minimally functional but if you'd like to fork it and get to work on it, feel free. 

Thanks for being considerate.

**Comment by wingchen** [comment]
thanks a lot. I am playing with it now :)
